In [2]:
import numpy as np
def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def  mult(a,b):
    return a*b
def div(a,b):
    return a/b
a=input(np.array)
b=input(np.array)
a = np.array(input("Enter first array: ").split(), dtype=int)
b = np.array(input("Enter second array: ").split(), dtype=int)

print("Addition:", add(a, b))#addin
print("Subtraction:", sub(a, b))#subtraction
print("Multiplication:", mult(a, b))
print("Division:", div(a, b))
     

Addition: [6912]
Subtraction: [-4444]
Multiplication: [7006652]
Division: [0.21733005]


In [1]:
import numpy as np

# Create array
arr = np.array([1,2,3,4,5,6])

# Slicing
print("Slicing:")
print(arr[1:5])

# Reshaping
reshaped = arr.reshape(2,3)
print("\nReshaped Array:")
print(reshaped)

# Broadcasting
broadcasted = reshaped + 10
print("\nBroadcasting:")
print(broadcasted)



Slicing:
[2 3 4 5]

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Broadcasting:
[[11 12 13]
 [14 15 16]]
